name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        runs-on: [self-hosted, ubuntu-latest]

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install -T 132 -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -fae